name: $GCE_INSTANCE_NAME
driver:
  name: google
  private-ip-interface: ens4
  options:
    google-project: $GCE_PROJECT_ID
    google-zone: $GCE_ZONE
    google-tags: tsuru
    google-disk-size: 20
docker-storage-driver: overlay
docker-flags:
  - experimental
  - log-driver gcplogs
  - log-opt gcp-log-cmd=true
  - log-opt labels=integration-test
hosts:
  apps:
    size: 1
components:
  install-dashboard: false
  tsuru-image: tsuru/api:$TSURUVERSION
  tsuru:
    config:
      debug: true
      iaas:
        dockermachine:
          debug: true
