name: $GCE_INSTANCE_NAME
driver:
  name: google
  private-ip-interface: ens4
  options:
    google-project: $GCE_PROJECT_ID
    google-zone: $GCE_ZONE
    google-tags: tsuru
    google-disk-size: 20
    google-machine-type: $GCE_MACHINE_TYPE
docker-storage-driver: overlay
docker-install-url: https://releases.rancher.com/install-docker/17.09.sh
docker-flags:
  - experimental
  - log-driver gcplogs
  - log-opt gcp-log-cmd=true
  - log-opt labels=integration-test
hosts:
  apps:
    size: 1
  core:
    driver:
      options:
        google-scopes:
          - https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/compute,https://www.googleapis.com/auth/cloud-platform
components:
  install-dashboard: false
  tsuru-image: tsuru/api:$TSURUVERSION
  tsuru:
    config:
      debug: true
      iaas:
        dockermachine:
          debug: true
